version: '3.8'

services:
  api:
    build: .
    ports:
      - "8089:8080"
    depends_on:
      - notification
      - db
    env_file:
      - .env

  notification:
    image: greenbone/exercise-admin-notification
    ports:
      - "8081:8080"

  db:
    image: postgres:16.9
    ports:
      - "5452:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - './scripts/database/:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'

volumes:
  pgdata:
